guards:
- additional_guard_config: null
  description: Guard transferred from Playground 6995e58d0204ade0c5f7b80a
  is_agentic: false
  name: Prompt tokens
  ootb_type: token_count
  stage: prompt
  type: ootb
- additional_guard_config: null
  description: Guard transferred from Playground 6995e58d0204ade0c5f7b80a
  is_agentic: false
  name: Response tokens
  ootb_type: token_count
  stage: response
  type: ootb
